spring:
   application.name: bookmarks
   profiles.active: development
   jackson.serialization.write-dates-as-timestamps: false
   datasource:
     testOnBorrow: true
     validationQuery: SELECT 1
   main:
     web-environment: true


security:
  require-ssl: true
  sessions: stateless

management:
  port: 8081
  address: 127.0.0.1
  context-path: /actuator

endpoints:
  health:
    enabled: false

---

spring:
  profiles: staging

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}

  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---

spring:
  profiles: development

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmarks
    username: root
    password: password

  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update

---

spring:
  profiles: test

  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:bookmarks
    username: sa
    password:

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update