spring:
   application.name: bookmarks
   profiles.active: development
   jackson.serialization.write-dates-as-timestamps: false
   main:
     web-environment: true

security:
  require-ssl: true
  sessions: stateless

---

spring:
  profiles: development

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookmarks
    username: root
    password: password

  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update

---

spring:
  profiles: test

  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:bookmarks
    username: sa
    password:

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update